#ifndef GAME_STATES_H
#define GAME_STATES_H

typedef enum GameState
{
    STATE_MAIN_MENU,
    STATE_PLAYER_SELECTION_MENU,
    STATE_TOWN_MENU,
    STATE_MAP_MENU,
    STATE_QUEST_MENU,
    STATE_SHOP_MENU,

    STATE_QUIT

} GameState;

#endif // GAME_STATES_H